// webviews/src/app/modules/coe/components/live-graph/live-graph.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { FormGroup } from '@angular/forms';
import { CoSimulationConfig, LiveGraph } from 'src/app/modules/shared/classes/configuration/co-simulation-config';
import { InstanceScalarPair, ScalarVariable, CausalityType, ScalarVariableType, Instance } from 'src/app/modules/shared/classes/models/fmu';

@Component({
    selector: 'app-live-graph',
    templateUrl: './live-graph.component.html',
    styleUrls: ['./live-graph.component.scss']
})
export class LiveGraphComponent {

    @Input()
    graph!: LiveGraph;

    @Input()
    config!: CoSimulationConfig;

    /* set path(config: CoSimulationConfig) {
         this.config = config;
   
         if (config)
             this.parseconfig();
     }
     get path(): CoSimulationConfig {
         return this.config;
     }*/


    @Input()
    formGroup!: FormGroup;


    _editing: boolean = false;
    @Input()
    editing: boolean = false;


    outputPorts: Array<InstanceScalarPair> = [];

    /* parseconfig() {
         // Create an array of all output ports on all instances
         this.outputPorts = this.config.multiModel.fmuInstances
             .map(instance => instance.fmu.scalarVariables
                 .filter(sv => sv.type === ScalarVariableType.Real && (sv.causality === CausalityType.Output || sv.causality === CausalityType.Parameter))
                 .map(sv => this.config.multiModel.getInstanceScalarPair(instance.fmu.name, instance.name, sv.name)))
             .reduce((a, b) => a.concat(...b), []);
     }
   */
    liveStreamSearchName: string = '';

    customTrackBy(index: number, obj: any): any {
        return index;
    }

    getOutputs(scalarVariables: Array<ScalarVariable>) {
        return scalarVariables.filter(variable => (variable.causality === CausalityType.Output || variable.causality === CausalityType.Local));
    }

    isLocal(variable: ScalarVariable): boolean {
        return variable.causality === CausalityType.Local
    }

    getScalarVariableTypeName(type: ScalarVariableType) {
        return ScalarVariableType[type];
    }

    restrictToCheckedLiveStream(instance: Instance, scalarVariables: Array<ScalarVariable>) {
        return scalarVariables.filter(variable => this.isLivestreamChecked(instance, variable));
    }

    isLivestreamChecked(instance: Instance, output: ScalarVariable) {
        let variables = this.graph.getLivestream().get(instance);

        if (!variables) return false;

        return variables.indexOf(output) !== -1;
    }

    onLivestreamChange(enabled: boolean, instance: Instance, output: ScalarVariable) {
        let variables = this.graph.getLivestream().get(instance);

        if (!variables) {
            variables = [];
            this.graph.getLivestream().set(instance, variables);
        }

        if (enabled)
            variables.push(output);
        else {
            variables.splice(variables.indexOf(output), 1);

            if (variables.length == 0)
                this.graph.getLivestream().delete(instance);
        }
    }

    onLiveStreamKey(event: any) {
        this.liveStreamSearchName = event.target.value;
    }

}

<div class="form-horizontal" [formGroup]="formGroup">
    <div class="form-group">
        <div class="form-forizontal">
            <div *ngIf="editing" class="form-group">
                <label class="col-md-4 col-sm-5 control-label" style="text-align: right">Filter</label>
                <input #box (keyup)="onLiveStreamKey($event)" class="col-sm-7 col-md-8 form-control">
            </div>
        </div>
    </div>


    <div class="form-group">
        <div class="form-horizontal">
            <div class="form-group">
                <label class="col-sm-5 col-md-4 control-label">Name:</label>
                <p *ngIf="!editing" class="form-control-static col-sm-7 col-md-8">{{graph.title}}</p>
               <!--  <input *ngIf="editing" [(ngModel)]="graph.title" formControlName="title" class="form-control col-sm-7 col-md-8"> -->
                <!-- See this post regarding [ngModelOptions]="{standalone: true}"
                     https://stackoverflow.com/questions/38365761/angular2-use-ngmodel-with-ngmodeloptions-standalone-true-to-link-to-a -->
                     <input *ngIf="editing" [(ngModel)]="graph.title" name="title" class="form-control col-sm-7 col-md-8" [ngModelOptions]="{standalone: true}">
            </div>
            <div class="form-group">
                <label class="col-sm-5 col-md-4 control-label">External Window</label>
                <div class="checkbox col-sm-7 col-md-8">
                    <label>
                                <!-- <input type="checkbox" [disabled]="!editing" name="externalWindow" [checked]="graph.externalWindow"
                        formControlName="externalWindow" > -->
                        <input name="externalWindow" [(ngModel)]="graph.externalWindow" [ngModelOptions]="{standalone: true}" type="checkbox" [disabled]="!editing" [checked]="graph.externalWindow">
                    </label>
                </div>
            </div>
            <div class="form-group" *ngFor="let instance of config.multiModel.fmuInstances">
                <label class="col-sm-5 col-md-4 control-label">{{instance.fmu.name}}.{{instance.name}}</label>
                <div class="col-sm-7 col-md-8">
                    <div *ngFor="let output of (editing ? getOutputs(instance.fmu.scalarVariables) : restrictToCheckedLiveStream(instance,getOutputs(instance.fmu.scalarVariables)) )">

                        <div class="checkbox" *ngIf="output.name.includes(liveStreamSearchName)">
                            <label>
                                <!--PL-TODO 
                                        <input type="checkbox"
                                                [disabled]="!editing"
                                                [checked]="isLivestreamChecked(instance, output)"
                                                (change)="onLivestreamChange($event.target?.checked, instance, output)" id="{{instance.name}}{{output.name}}">
                                -->
                                
                                                <span *ngIf="isLocal(output)" class="text-warning" style="color:#f0ad4e!important" title="Name: {{output.name}}, Causality: {{output.causality}}, Type: {{getScalarVariableTypeName(output.type)}}">{{output.name}}</span>
                                                <span *ngIf="!isLocal(output)" title="Name: {{output.name}}, Causality: {{output.causality}}, Type: {{getScalarVariableTypeName(output.type)}}">{{output.name}}</span>
                                    </label>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

// components/src/coe/live-graph/live-graph.tsx
import React, { Component, useState } from 'react';

type LiveGraphComponent_prop = {
  graph: any
  config: any
  formGroup: any
  editing: boolean 
}

export const LiveGraphComponent: React.FunctionComponent<LiveGraphComponent_prop> = ({graph, config, formGroup, editing}) =>
{
    const [liveStreamSearchName, setLiveStreamSearchName] = useState('');
    
    const customTrackBy = (index: number, obj: any) => index;
    
    const getOutputs = (scalarVariables: any) => {
        return scalarVariables.filter(
            (variable: any) =>
                variable.causality === 'Output' || variable.causality === 'Local'
        );
    };
    
    const isLocal = (variable: any): boolean => {
        return variable.causality === 'Local';
    };
    
    const getScalarVariableTypeName = (type:any) => {
        //FIXME return ScalarVariableType[type];
        return type;
    };
    
    const restrictToCheckedLiveStream = (instance: any, scalarVariables: any) => {
        return scalarVariables.filter((variable: any) =>
            isLivestreamChecked(instance, variable)
        );
    };
    
    const isLivestreamChecked = (instance: any, output:any) => {
        let variables = graph.getLivestream().get(instance);
    
        if (!variables) return false;
    
        return variables.indexOf(output) !== -1;
    };
    
    const onLivestreamChange = (enabled: boolean, instance: any, output: any) => {
        let variables = graph.getLivestream().get(instance);
    
        if (!variables) {
            variables = [];
            graph.getLivestream().set(instance, variables);
        }
    
        if (enabled) variables.push(output);
        else {
            variables.splice(variables.indexOf(output), 1);
    
            if (variables.length === 0)
                graph.getLivestream().delete(instance);
        }
    };
    
    const onLiveStreamKey = (event: any) => {
        setLiveStreamSearchName(event.target.value);
    };
    
    return (
      <div className="form-horizontal" //FIXMEformGroup={formGroup}
      >
      <div className="form-group">
        <div className="form-horizontal">
          <div className="form-group">
            <label className="col-sm-5 col-md-4 control-label">Name:</label>
            <p className="form-control-static col-sm-7 col-md-8">{editing ? graph.title : ''}</p>
            {editing && (
              <input
                className="form-control col-sm-7 col-md-8"
                name="title"
                value={graph.title}
                //onChange={(e) => this.onTitleChange(e.target.value)}
              />
            )}
          </div>
          <div className="form-group">
            <label className="col-sm-5 col-md-4 control-label">External Window</label>
            <div className="checkbox col-sm-7 col-md-8">
              <label>
                <input
                  name="externalWindow"
                  type="checkbox"
                  disabled={!editing}
                  checked={graph.externalWindow}
                  //onChange={(e) => this.onExternalWindowChange(e.target.checked)}
                />
              </label>
            </div>
          </div>
          
          {config.multiModel.fmuInstances.map((instance: any, index: number) => ( //FIXME fmuinstances not defined
            <div className="form-group" key={index}>
              <label className="col-sm-5 col-md-4 control-label">
                {instance.fmu.name}.{instance.name}
              </label>
              <div className="col-sm-7 col-md-8">
                {editing
                  ? getOutputs(instance.fmu.scalarVariables).map((output: any, outIndex: number) => (
                      <div className="checkbox" key={outIndex}>
                        <label>
                          <span
                            className={isLocal(output) ? 'text-warning' : ''}
                            title={`Name: ${output.name}, Causality: ${output.causality}, Type: ${getScalarVariableTypeName(output.type)}`}
                          >
                            {output.name}
                          </span>
                        </label>
                      </div>
                    ))
                  : restrictToCheckedLiveStream(instance, getOutputs(instance.fmu.scalarVariables)).map((output: any, outIndex: number) => (
                      <div className="checkbox" key={outIndex}>
                        <label>
                          <span
                            className={isLocal(output) ? 'text-warning' : ''}
                            title={`Name: ${output.name}, Causality: ${output.causality}, Type: ${getScalarVariableTypeName(output.type)}`}
                          >
                            {output.name}
                          </span>
                        </label>
                      </div>
                    ))}
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};

export default LiveGraphComponent;
