// components/src/coe/fmu-max-step-size/fmu-max-step-size.tsx
import React from 'react';

class FmuMaxStepSizeComponent extends React.Component<FmuMaxStepSizeComponentProps> {
  constructor(props: any) {
    super(props);
  }

  render() {
    const { constraint, formGroup, editing } = this.props;

    const customTrackBy = (index: number, obj: any) => {
      return index;
    };

    return (
      <div>
        <div className="form-group">
          <label className="col-sm-12 control-label" style={{ textAlign: 'left' }}>
            Constrain Step Size to Maximum bound of FMUs
          </label>
        </div>
        <hr />
        <div className="form-horizontal">
          <div className="form-group">
            <div className="col-sm-9">
              <p className="form-control-static">Constraint enabled.</p>
            </div>
          </div>
        </div>
      </div>
    );
  }
}

// Define prop types for type checking
type FmuMaxStepSizeComponentProps = {
  constraint: any,
  formGroup: any,
  editing: boolean
};

export default FmuMaxStepSizeComponent;

// webviews/src/app/modules/coe/components/fmu-max-step-size/fmu-max-step-size.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { FormGroup } from '@angular/forms';
import { FmuMaxStepSizeConstraint } from 'src/app/modules/shared/classes/co-simulation-config';

@Component({
  selector: 'app-fmu-max-step-size',
  templateUrl: './fmu-max-step-size.component.html',
  styleUrls: ['./fmu-max-step-size.component.scss']
})
export class FmuMaxStepSizeComponent {

  @Input()
  constraint!: FmuMaxStepSizeConstraint;

  @Input()
  formGroup!: FormGroup;

  @Input()
  editing: boolean = false;

  customTrackBy(index: number, obj: any): any {
    return index;
  }
  
}

<div class="form-group">
	<label class="col-sm-12 control-label" style="text-align: left">Constrain Step Size to Maximum bound of FMUs</label>
</div>
<hr>
<div class="form-horizontal" [formGroup]="formGroup">
	<div class="form-group">
		<div class="col-sm-9">
			<p class="form-control-static">Constraint enabled.</p>
		</div>
	</div>
</div>
