// webviews/src/app/modules/coe/components/bounded-difference/bounded-difference.tsx
import React, { useState } from 'react';
import { Checkbox, ComboBox, DefaultButton, TextField } from '@fluentui/react';
import { BoundedDifferenceConstraint } from 'src/app/modules/shared/classes/co-simulation-config';



//-----------INTERFACES-----------------
interface FormErrors {
	required?: boolean;
	notUnique?: string;
	invalidLength?: boolean;
	notUniquePorts?: boolean;
	invalidNumberAbstol?: boolean;
	invalidNumberReltol?: boolean;
	invalidNumberSafety?: boolean;
}
  
  interface Port {
	instance: {
	  fmu: {
		name: string;
	  };
	  name: string;
	  scalarVariable: {
		name: string;
	  };
	};
  }
  
  

  //----------------COMPONENT-----------------
export default function BoundedDifferenceReactComponent(props: any) {
	//state variables 
	const [formErrors, setFormErrors] = useState<FormErrors>({}); 
	const [constraint, setConstraint] = useState(props.constraint);
	const [editing, setEditing] = useState<boolean>(props.editing); //for testing if editing works - remove later 



	//-----------FUNCTIONS-----------------
	const handleIdChange = (e: React.FormEvent<HTMLInputElement | HTMLTextAreaElement>, newValue?: string) => {
		if (newValue !== undefined) {
			setConstraint((prevState: BoundedDifferenceConstraint) => ({ ...prevState, id: newValue }));
		}
	}

	const handleAbstolChange = (e: React.FormEvent<HTMLInputElement | HTMLTextAreaElement>, newValue?: string) => {
		if (newValue !== undefined) {
			setConstraint((prevState: BoundedDifferenceConstraint) => ({ ...prevState, abstol: newValue }));
		}
	}

	const handleReltolChange = (e: React.FormEvent<HTMLInputElement | HTMLTextAreaElement>, newValue?: string) => {
		if (newValue !== undefined) {
			setConstraint((prevState: BoundedDifferenceConstraint) => ({ ...prevState, reltol: newValue }));
		}
	}

	const handleSafetyChange = (e: React.FormEvent<HTMLInputElement | HTMLTextAreaElement>, newValue?: string) => {
		if (newValue !== undefined) {
			setConstraint((prevState: BoundedDifferenceConstraint) => ({ ...prevState, safety: newValue }));
		}
	}

	const handleSkipDiscreteChange = (e: React.FormEvent<HTMLInputElement | HTMLTextAreaElement>, isChecked?: boolean) => {
		if (isChecked !== undefined) {
			setConstraint((prevState: BoundedDifferenceConstraint) => ({ ...prevState, skipDiscrete: isChecked }));
		}
	}


	//----------------RENDER-----------------
	return (
		<div className="form-horizontal">

			{/* Start/Stop Editing button (REMOVE LATER) */}	
			<button onClick={() => setEditing(!editing)}>
				{editing ? "Stop Editing" : "Start Editing"}
			</button>

	
			{/* ID text field */}
			<div className="form-group">
				<label className="col-sm-3 control-label">ID</label>
				<div className="col-sm-9">
					{
						editing ? 
						<TextField value={constraint.id} onChange={handleIdChange} /> 
						:
						<span>{constraint.id}</span>
					}
					{formErrors.required && <span className="alert alert-danger">This field is required.</span>}
					{formErrors.notUnique && formErrors.notUnique === props.constraint.id && <span className="alert alert-danger">ID is not unique.</span>}
				</div>
			</div>

			{/* Ports text field */}
				<div className="form-group">
				<label className="col-sm-3 control-label">
					Ports
					{props.editing && <DefaultButton text="+" onClick={props.probs.addPort()} />}
				</label>
				<div className="col-sm-9">
					{
						props.ports.map((port: Port, index: number) => (
							<div key={index}>
								{
									editing ?
									<ComboBox 
										selectedKey={`${port.instance.fmu.name}.${port.instance.name}.${port.instance.scalarVariable.name}`}
										options={props.ports.map((output: Port) => ({
											key: `${output.instance.fmu.name}.${output.instance.name}.${output.instance.scalarVariable.name}`,
											text: `${output.instance.fmu.name}.${output.instance.name}.${output.instance.scalarVariable.name}`
										}))}
										onChange={(e, selectedItem) => props.props.onPortChange(e, selectedItem, index)}
									/>
									:                        
									<span>{`${port.instance.fmu.name}.${port.instance.name}.${port.instance.scalarVariable.name}`}</span>
								}
								{
									props.editing && props.constraint.ports.length > 1 && <DefaultButton text="-" onClick={() => props.props.removePort(port)} />}
							</div>
						))
					}
					{formErrors.invalidLength && <span className="alert alert-danger alert-standalone">1 or more ports are required.</span>}
					{formErrors.notUniquePorts && <span className="alert alert-danger">Ports are not unique.</span>}
				</div>
			</div>

			{/* Absolute Tolerance text field */}
			<div className="form-group">
				<label className="col-sm-3 control-label">Absolute Tolerance</label>
				<div className="col-sm-9">
					{
						editing ? 
						<TextField value={constraint.abstol} onChange={handleAbstolChange} />
						:
						<span>{constraint.abstol}</span>
					}
					{formErrors.invalidNumberAbstol && <span className="alert alert-danger">Only numbers are allowed.</span>}
				</div>
			</div>

			{/* Relative Tolerance text field */}
			<div className="form-group">
				<label className="col-sm-3 control-label">Relative Tolerance</label>
				<div className="col-sm-9">
					{
						editing ? 
						<TextField value={constraint.reltol} onChange={handleReltolChange}/>
						:
						<span>{constraint.reltol}</span>
					}
					{formErrors.invalidNumberReltol && <span className="alert alert-danger">Only numbers are allowed.</span>}
				</div>
			</div>
	
			{/* Safety text field */}
			<div className="form-group">
				<label className="col-sm-3 control-label">Safety</label>
				<div className="col-sm-9">
					{
						editing ? 
						<TextField value={constraint.safety} onChange={handleSafetyChange}/>
						:
						<span>{constraint.safety}</span>
					}
					{formErrors.invalidNumberSafety && <span className="alert alert-danger">Only numbers are allowed.</span>}
				</div>
			</div>


			{/* Skip discrete text field */}
            <div className="form-group">
                <label className="col-sm-3 control-label">Skip Discrete</label>
                <div className="col-sm-9">
                    <Checkbox 
                        checked={constraint.skipDiscrete} 
                        disabled={!editing} 
                        onChange={(e, isChecked) => setConstraint({ ...constraint, skipDiscrete: isChecked })} 
                    />
                </div>
            </div>
		</div>
	);
}

// webviews/src/app/modules/coe/components/bounded-difference/bounded-difference.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { FormControl, FormGroup } from '@angular/forms';
import { BoundedDifferenceConstraint } from 'src/app/modules/shared/classes/co-simulation-config';
import { InstanceScalarPair } from 'src/app/modules/shared/classes/fmu';

@Component({
    selector: 'app-bounded-difference',
    templateUrl: './bounded-difference.component.html',
    styleUrls: ['./bounded-difference.component.scss']
})
export class BoundedDifferenceComponent {
    
    @Input()
    constraint!: BoundedDifferenceConstraint;

    @Input()
    ports: Array<InstanceScalarPair> = [];

    @Input()
    formGroup!: FormGroup;

    @Input()
    editing: boolean = false;

    customTrackBy(index: number, obj: any): any {
        return index;
    }

    addPort() {
        this.constraint.ports.push(this.ports[0]);
        this.updatePortValidation();
    }

    removePort(port: InstanceScalarPair) {
        this.constraint.ports.splice(this.constraint.ports.indexOf(port), 1);
        this.updatePortValidation();
    }

    onPortChange(output: InstanceScalarPair, index: number) {
        this.constraint.ports[index] = output;
        this.updatePortValidation();
    }

    updatePortValidation() {
        let formControl = <FormControl>this.formGroup.get('ports');
        formControl.updateValueAndValidity();
    }

}

<div class="form-horizontal" [formGroup]="formGroup">
    <div class="form-group">
        <label class="col-sm-3 control-label">ID</label>
        <div class="col-sm-9">
            <p *ngIf="!editing" class="form-control-static">{{constraint.id}}</p>
            <input *ngIf="editing" [(ngModel)]="constraint.id" formControlName="id" class="form-control">
            <div *ngIf="formGroup.hasError('required', 'id')" class="alert alert-danger">This field is required.</div>
            <div *ngIf="formGroup.parent?.hasError('notUnique') && formGroup.parent?.errors?.['notUnique'] === constraint.id" class="alert alert-danger">ID is not unique.</div>
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-3 control-label">
            Ports
            <button *ngIf="editing" type="button" (click)="addPort()" class="btn btn-default btn-xs">
                <span class="glyphicon glyphicon-plus"></span>
            </button>
        </label>
        <div class="col-sm-9">
            <div *ngFor="let port of constraint.ports; let i=index; trackBy:customTrackBy">
                <p *ngIf="!editing" class="form-control-static">{{port.instance.fmu.name}}.{{port.instance.name}}.{{port.scalarVariable.name}}</p>
                <div *ngIf="editing" class="input-group">
                    <select [ngModel]="constraint.ports[i]" (ngModelChange)="onPortChange($event, i)" [ngModelOptions]="{standalone: true}" class="form-control">
                        <option *ngFor="let output of ports" [ngValue]="output">{{output.instance.fmu.name}}.{{output.instance.name}}.{{output.scalarVariable.name}}</option>
                    </select>
                    <span class="input-group-btn">
                    <button [disabled]="constraint.ports.length == 1" type="button" (click)="removePort(port)" class="btn btn-default">
                        <span class="glyphicon glyphicon-remove"></span>
                    </button>
                </span>
                </div>
            </div>
            <div *ngIf="formGroup.hasError('invalidLength', 'ports')" class="alert alert-danger alert-standalone">1 or more ports are required.</div>
            <div *ngIf="formGroup.hasError('notUnique', 'ports')" class="alert alert-danger">Ports are not unique.</div>
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-3 control-label">Absolute Tolerance</label>
        <div class="col-sm-9">
            <p *ngIf="!editing" class="form-control-static">{{constraint.abstol}}</p>
            <input *ngIf="editing" [(ngModel)]="constraint.abstol" formControlName="abstol" class="form-control">
            <div *ngIf="formGroup.hasError('invalidNumber', 'abstol')" class="alert alert-danger">Only numbers are allowed.</div>
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-3 control-label">Relative Tolerance</label>
        <div class="col-sm-9">
            <p *ngIf="!editing" class="form-control-static">{{constraint.reltol}}</p>
            <input *ngIf="editing" [(ngModel)]="constraint.reltol" formControlName="reltol" class="form-control">
            <div *ngIf="formGroup.hasError('invalidNumber', 'reltol')" class="alert alert-danger">Only numbers are allowed.</div>
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-3 control-label">Safety</label>
        <div class="col-sm-9">
            <p *ngIf="!editing" class="form-control-static">{{constraint.safety}}</p>
            <input *ngIf="editing" [(ngModel)]="constraint.safety" formControlName="safety" class="form-control">
            <div *ngIf="formGroup.hasError('invalidNumber', 'safety')" class="alert alert-danger">Only numbers are allowed.</div>
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-3 control-label">Skip Discrete</label>
        <div class="col-sm-9">
            <input [disabled]="!editing" [(ngModel)]="constraint.skipDiscrete" formControlName="skipDiscrete" type="checkbox">
        </div>
    </div>
</div>
